/* ProjectHearth SQL Server bootstrap schema */
CREATE TABLE sessions (
  session_id UNIQUEIDENTIFIER PRIMARY KEY,
  user_id NVARCHAR(128) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE messages (
  message_id UNIQUEIDENTIFIER PRIMARY KEY,
  session_id UNIQUEIDENTIFIER NOT NULL,
  role NVARCHAR(32) NOT NULL,
  content NVARCHAR(MAX) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  CONSTRAINT fk_messages_sessions FOREIGN KEY (session_id) REFERENCES sessions(session_id)
);

CREATE TABLE tasks (
  task_id UNIQUEIDENTIFIER PRIMARY KEY,
  session_id UNIQUEIDENTIFIER NOT NULL,
  status NVARCHAR(32) NOT NULL,
  input NVARCHAR(MAX) NOT NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE task_events (
  event_id UNIQUEIDENTIFIER PRIMARY KEY,
  task_id UNIQUEIDENTIFIER NOT NULL,
  event_type NVARCHAR(64) NOT NULL,
  payload NVARCHAR(MAX) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE tool_invocations (
  invocation_id UNIQUEIDENTIFIER PRIMARY KEY,
  task_id UNIQUEIDENTIFIER NOT NULL,
  tool_name NVARCHAR(128) NOT NULL,
  mode NVARCHAR(16) NOT NULL,
  request_payload NVARCHAR(MAX) NULL,
  response_payload NVARCHAR(MAX) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE entities (
  entity_id UNIQUEIDENTIFIER PRIMARY KEY,
  entity_type NVARCHAR(64) NOT NULL,
  entity_key NVARCHAR(255) NOT NULL,
  data NVARCHAR(MAX) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE memory_index_metadata (
  index_id UNIQUEIDENTIFIER PRIMARY KEY,
  memory_type NVARCHAR(64) NOT NULL,
  backend NVARCHAR(64) NOT NULL,
  metadata NVARCHAR(MAX) NULL,
  created_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE app_settings (
  setting_key NVARCHAR(128) PRIMARY KEY,
  setting_value NVARCHAR(MAX) NULL,
  updated_at DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
